### PR TITLE
Feature request: extend options for pimatic-mail plugin

### PR DESCRIPTION
**Pull request by mwittig**
This pull request implements the following:
- update to nodemailer0.7.1
- added "file" modifier which allows for attaching a file
- added "html" modifier which allows for adding a HTML text body.
- "to" and "file" modifiers may be used multiple times to defined mutiple recipinet and/or multiple attachments
- now, modifiers can be provided in arbritary order
- added configuration example for GMX

See also: http://forum.pimatic.org/topic/797/extend-options-for-pimatic-mail-plugin

### CODE REVIEW

**Comment by mwittig** [comment]
@sweetpi You probably wonder why I decided to split "to" or "from" modfiers into individual items in "optionsTokens" (by adding an index value to the key) rather than simply pushing a value to the tokens array. The reason is that I wanted to make sure that even e-mail address and file-path values will be evaluated using  "variableManager.evaluateStringExpression()". However, if you pass an array of "to" modifier values to it the result will be one string which would be difficults to split properly. You would need to add a separator item to the tokens array before evaluating the expression. I tried this but it conflicted with the tokenization of a variable expression as part of the e-mail address value.

**Comment by sweetpi** [comment]
Wow very nice. The implementation of the matching is a little bit funky. Took me a while to understand it :D. 

I think the matching:

``` coffeescript
      # list of action option patterns derived for @mailOptionKeys
      # if a pattern has been matched it will be removed unless the option
      # may occur multiple times as it is the case for "to" and "file"
      mailOptionsPatterns = []
      for key in @mailOptionKeys
        mailOptionsPatterns.push " #{key}:"

      condition = true
      index = 0
      while condition
        next = m.match(mailOptionsPatterns).matchStringWithVars( (m, tokens) =>
          matchedOptionPattern = m.elements[m.elements.length - 2].match;
          opt = matchedOptionPattern.replace(/^[\s\uFEFF\xA0]+|[\:]+$|[\s\uFEFF\xA0]+$/g, '')
          optionsSet.push opt
          unless opt is "file" or opt is "to"
            optionsTokens[opt] = tokens
            # remove matched pattern from mailOptionsPatterns as all options except file may only occur once
            mailOptionsPatterns = mailOptionsPatterns.filter (item) -> item isnt matchedOptionPattern
          else
            optionsTokens[opt + index++] = tokens
        )
        condition = next.hadMatch()
        m = next if condition
```

could be rewritten as (untested):

``` coffeescript
      # list of action option patterns derived for @mailOptionKeys
      # if a pattern has been matched it will be removed unless the option
      # may occur multiple times as it is the case for "to" and "file"
      mailOptionsPatterns = []
      for key in @mailOptionKeys
        # matcher can also take a pair of key and pattern instead of a pattern only.
        mailOptionsPatterns.push [key, " #{key}:"]

      condition = true
      index = 0
      while condition
        next = null
        m.match(mailOptionsPatterns, (m, opt) => 
          m.matchStringWithVars( (m, tokens) =>
            optionsSet.push opt
            unless opt is "file" or opt is "to"
              optionsTokens[opt] = tokens
              # remove matched pattern from mailOptionsPatterns as all options except file may only occur once
              mailOptionsPatterns = mailOptionsPatterns.filter (item) -> item[0] isnt key
            else
              # we could make this an array...
              optionsTokens[opt + index++] = tokens
            next = m
          )
        )
        condition = next?
        m = next if condition
```

I know the matcher is fairly undocumented...

Do you want to give it a try?

**Comment by mwittig** [comment]
Hi Oliver. Thanks a lot for looking into this and for the guidance. I am not satisfied at all with my implementation ("funky" describes it well).  I'll have a look at your proposal later and will give it a try. Obviously, your code looks cleaner.

**Comment by mwittig** [comment]
Hi,

It worked almost. See Revised code below (changes maked with ^^^)

```
while condition
        next = null
        m.match(mailOptionsPatterns, (m, matchedOptionPattern) =>
                                         ^^^ (renamed opt to matchedOptionPattern)
          m.matchStringWithVars( (m, tokens) =>
            opt = matchedOptionPattern.replace(/^[\s\uFEFF\xA0]+|[\:]+$|[\s\uFEFF\xA0]+$/g, '')
            ^^^ (added line)
            optionsSet.push opt
            unless opt is "file" or opt is "to"
              optionsTokens[opt] = tokens
              # remove matched pattern from mailOptionsPatterns as all options except file may only occur once
              mailOptionsPatterns = mailOptionsPatterns.filter (item) -> item isnt matchedOptionPattern
                                                                          ^^^ (replaced item[0] with item)
            else
              # we could make this an array...
              optionsTokens[opt + index++] = tokens
            next = m
          )
        )
        condition = next?
        m = next if condition
```

Unfortunately, the regex pattern replacement of matchedOptionPattern is required as it contains the modifier token, e.g. " file:". However for "opt" I need the option key, e.g. "file". I also had to chang the mailOptionsPatterns filter condition expression as otherwise the removal of unary modifier already used did not work. I am going to push my changes now.

Maybe, we simplify the regex `/^[\s\uFEFF\xA0]+|[\:]+$|[\s\uFEFF\xA0]+$/g` which I sneaked from jQuery. Following http://stackoverflow.com/questions/31533008/js-regular-expression-s-ufeff-xa0-makes-firefox-and-chrome-busy it is said "According to ECMA 5.1 specification, \s includes WhiteSpace and LineTerminator, and WhiteSpace includes U+FEFF and U+00A0 in its definition.". So, my understanding is that the following should do: `/^\s+|\:+$|\s+$/g`. I think it even can be simplified further to `/^\s+|\:+$/g`. What do you think?

EDIT: Just tested the simplified regex which works fine for me (have pushed my change).

**Comment by sweetpi** [comment]
Sorry I wasn't such clear. My idea was to make `mailOptionsPatterns` an array of pairs of key and pattern instead of just patterns:

``` coffeescript
mailOptionsPatterns.push [key, " #{key}:"]
```

If the matcher gets an array of arrays (array of pairs of key and pattern) it uses the pattern for matching but returns the key as match. So if we then use `m.match(mailOptionsPatterns, (m, opt) => ...` the pattern is used for matching, but `opt` is the key. So we don't need to obtain the key from the pattern and we don't need an regexp at all.

Example:

```
m.match([['file', ' file:'], ['to', ' to:']], (m, opt) => ...
```

matches " file:" and  " to:" but does return "file" respectively "to" as `opt` on match.

**Comment by mwittig** [comment]
Oh my gosh! I have missed this point in your earlier post. I fixed this now and it works fine. Thanks!

**Comment by sweetpi** [comment]
Thank you for the update. Published the new version.

**Pull request merged**
